/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6p2_hectorhernandez_12211096;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Hector
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_categoria.getModel();
        modelo.addElement(new Categoria("Panaderia"));
        cb_categoria.setModel(modelo);
        JugadoresDefault();
        LlenarArbol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        popup_menu = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        Seleccionar = new javax.swing.JMenuItem();
        Enviar_Solicitud = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_categorias = new javax.swing.JTree();
        jProgressBar1 = new javax.swing.JProgressBar();
        bt_alimentar = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_jugadores = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jl_alimentos = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jl_billeteras = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jftf_costo = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jftf_calorias = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        cb_categoria = new javax.swing.JComboBox<>();
        bt_crear_alimento = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtf_nomcategoria = new javax.swing.JTextField();
        bt_crear_categoria = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jftf_consumomaximo = new javax.swing.JFormattedTextField();
        bt_crear_billetera = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jftf_costbilletera = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        bt_aceptar_solicitud = new javax.swing.JButton();
        bt_rechazar_solicitud = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jl_amigos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        Eliminar.setText("jMenuItem1");
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });
        popup_menu.add(Eliminar);

        Seleccionar.setText("jMenuItem2");
        Seleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeleccionarMouseClicked(evt);
            }
        });
        popup_menu.add(Seleccionar);

        Enviar_Solicitud.setText("jMenuItem3");
        Enviar_Solicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Enviar_SolicitudMouseClicked(evt);
            }
        });
        popup_menu.add(Enviar_Solicitud);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Root");
        jt_categorias.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_categorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_categoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_categorias);

        bt_alimentar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bt_alimentar.setLabel("Alimentar");
        bt_alimentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alimentarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("1000");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("0");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("500");

        jl_jugadores.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(jl_jugadores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(20, 20, 20))
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bt_alimentar, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(1, 1, 1)
                        .addComponent(bt_alimentar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Juego", jPanel1);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Puntos de Consumo: ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("0");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Comprar");

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("Comprar");

        jl_alimentos.setModel(new DefaultListModel());
        jScrollPane8.setViewportView(jl_alimentos);

        jl_billeteras.setModel(new DefaultListModel());
        jScrollPane9.setViewportView(jl_billeteras);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tienda", jPanel2);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setText("Crear Alimento");

        jtf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombreActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel8.setText("Nombre");

        jLabel9.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel9.setText("Costo");

        jLabel10.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel10.setText("Calorias");

        jLabel11.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel11.setText("Categoria");

        bt_crear_alimento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_crear_alimento.setText("Crear");
        bt_crear_alimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crear_alimentoMouseClicked(evt);
            }
        });
        bt_crear_alimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crear_alimentoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel12.setText("Crear Categoria");

        jLabel13.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel13.setText("Nombre de Categoria");

        bt_crear_categoria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_crear_categoria.setText("Crear");
        bt_crear_categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crear_categoriaMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel14.setText("Crear Billetera");

        jLabel15.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel15.setText("Consumo Maximo");

        jftf_consumomaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftf_consumomaximoActionPerformed(evt);
            }
        });

        bt_crear_billetera.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_crear_billetera.setText("Crear");
        bt_crear_billetera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crear_billeteraMouseClicked(evt);
            }
        });
        bt_crear_billetera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crear_billeteraActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel16.setText("Costo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jftf_costbilletera, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_nombre)
                                    .addComponent(cb_categoria, 0, 149, Short.MAX_VALUE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jftf_consumomaximo)
                                    .addComponent(jtf_nomcategoria))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(bt_crear_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jftf_costo)
                                            .addComponent(jftf_calorias, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                                    .addComponent(bt_crear_billetera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(bt_crear_alimento, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jftf_costo)
                            .addComponent(jtf_nombre))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jftf_calorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(bt_crear_alimento, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nomcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_crear_categoria))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftf_consumomaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_crear_billetera))
                .addGap(8, 8, 8)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jftf_costbilletera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crafteo", jPanel3);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel17.setText("Amigos");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel18.setText("Solicitudes de amistad");

        bt_aceptar_solicitud.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bt_aceptar_solicitud.setText("Aceptar");

        bt_rechazar_solicitud.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bt_rechazar_solicitud.setText("Rechazar");

        jl_amigos.setModel(new DefaultListModel());
        jScrollPane10.setViewportView(jl_amigos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(bt_aceptar_solicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt_rechazar_solicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_aceptar_solicitud)
                    .addComponent(bt_rechazar_solicitud))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Amigos", jPanel4);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("Simulador de Engordar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_alimentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alimentarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_alimentarActionPerformed

    private void bt_crear_alimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crear_alimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_crear_alimentoActionPerformed

    private void jftf_consumomaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftf_consumomaximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftf_consumomaximoActionPerformed

    private void bt_crear_billeteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crear_billeteraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_crear_billeteraActionPerformed

    private void jtf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombreActionPerformed

    private void bt_crear_categoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crear_categoriaMouseClicked
        // TODO add your handling code here:

        String nom_categoria;
        nom_categoria = jtf_nomcategoria.getText();

        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_categoria.getModel();
        model.addElement(new Categoria(nom_categoria));
        jtf_nomcategoria.setText("");

        JOptionPane.showMessageDialog(rootPane, "Categoria Creada Exitosamente");
    }//GEN-LAST:event_bt_crear_categoriaMouseClicked
    private void LlenarArbol() {
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Categorias");
        for (int i = 0; i < cat.size(); i++) {
            DefaultMutableTreeNode nodo_categoria;
            nodo_categoria = new DefaultMutableTreeNode(cat.get(i));

            for (int j = 0; j < ali.size(); j++) {
                if (ali.get(j).getCategoria() == cat.get(i)) {
                    DefaultMutableTreeNode nodo_alimento;
                    nodo_alimento = new DefaultMutableTreeNode(ali.get(j));
                    for (int k = 0; k < jug.size(); k++) {
                        if (jug.get(k).getAlimento() == ali.get(j)) {
                            DefaultMutableTreeNode nodo_jugador;
                            nodo_jugador = new DefaultMutableTreeNode(jug.get(k));
                            nodo_alimento.add(nodo_jugador);
                        }
                    }
                    nodo_categoria.add(nodo_alimento);
                }
            }
            raiz.add(nodo_categoria);
        }
        DefaultTreeModel modelo = new DefaultTreeModel(raiz);
        modelo.reload();
        jt_categorias.setModel(modelo);
    }
    
    private void bt_crear_billeteraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crear_billeteraMouseClicked
        // TODO add your handling code here:
        int consumo_maximo;
        int costo;
        try {
            consumo_maximo = Integer.parseInt(jftf_consumomaximo.getText());
            costo = Integer.parseInt(jftf_costbilletera.getText());

            Billetera billetera = new Billetera(consumo_maximo, costo);
            bi.add(billetera);
            DefaultListModel modelo = (DefaultListModel) jl_billeteras.getModel();
            modelo.addElement(new Billetera(consumo_maximo, costo));
            

            jftf_consumomaximo.setText("");
            jftf_costbilletera.setText("");
            cargarLista();

            JOptionPane.showMessageDialog(rootPane, "Billetera Creada Exitosamente");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error!");
        }
    }//GEN-LAST:event_bt_crear_billeteraMouseClicked
    private void cargarLista(){
        DefaultListModel modelo = (DefaultListModel) jl_billeteras.getModel();
        modelo.removeAllElements();
        
        for (Billetera billetera : bi) {
            modelo.addElement(billetera);
        }       
    }
    private void bt_crear_alimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crear_alimentoMouseClicked
        // TODO add your handling code here:
        try {
            String nombre;
            Categoria categoria;
            int costo;
            int calorias;

            nombre = jtf_nombre.getText();
            categoria = (Categoria) cb_categoria.getSelectedItem();
            costo = Integer.parseInt(jftf_costo.getText());
            calorias = Integer.parseInt(jftf_calorias.getText());

            Alimento alimentos = new Alimento(nombre, categoria, costo, calorias);
            ali.add(alimentos);
            DefaultListModel modelo = (DefaultListModel) jl_alimentos.getModel();
            modelo.addElement(new Alimento(nombre, categoria, costo, calorias));

            jtf_nombre.setText("");
            cb_categoria.setSelectedItem("");
            jftf_costo.setText("");
            jftf_calorias.setText("");

            cargarLista();

            JOptionPane.showMessageDialog(rootPane, "Alimento Creado Exitosamente");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error!");
        }
    }//GEN-LAST:event_bt_crear_alimentoMouseClicked

    private void jt_categoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_categoriasMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = jt_categorias.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_categorias.setSelectionRow(row);
            Object v1 = jt_categorias.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Jugador) {
                persona_seleccionada = (Jugador) nodo_seleccionado.getUserObject();
                popup_menu.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jt_categoriasMouseClicked

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_EliminarMouseClicked

    private void SeleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeleccionarMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_SeleccionarMouseClicked

    private void Enviar_SolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Enviar_SolicitudMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_Enviar_SolicitudMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void JugadoresDefault(){
        //bi billeteras
        //cat categorias
        //ali alimentos
        //jug jugadores
        
        //Billetera
        bi.add(new Billetera(1000,500));
        //Categorias
        cat.add(new Categoria("Pastas"));
        cat.add(new Categoria("Reposteria"));
        
        //Para Pastas
        ali.add(new Alimento("Lazaña", cat.get(0), 145, 399));
        ali.add(new Alimento("Caracolitos", cat.get(0), 20, 100));
        ali.add(new Alimento("Tornillitos", cat.get(0), 25, 140));
        ali.add(new Alimento("Spaguettis", cat.get(0), 30, 150));
        ali.add(new Alimento("Marmahon", cat.get(0), 35, 179));
        //Para Reposteria
        ali.add(new Alimento("Cheseecake", cat.get(1), 75, 340));
        ali.add(new Alimento("Pastel Selva Negra", cat.get(1), 59, 380));
        ali.add(new Alimento("Pastelito de Piña", cat.get(1), 40, 400));
        ali.add(new Alimento("Dona Glaseada", cat.get(1), 35, 358));
        ali.add(new Alimento("Mil Hojas", cat.get(1), 60, 500));
        //Jugadores
        jug.add(new Jugador("Hector", "12211096", 10, 350, ali.get(0), bi.get(0)));
        jug.add(new Jugador("Diviana", "12137458", 45, 500, ali.get(1), bi.get(0)));
        jug.add(new Jugador("Santos", "12211876", 5, 550, ali.get(2), bi.get(0)));
        jug.add(new Jugador("Carlos", "12347658", 32, 400, ali.get(3), bi.get(0)));
        jug.add(new Jugador("Enrique", "12489760", 18, 239, ali.get(4), bi.get(0)));
        
        jug.add(new Jugador("Pamela", "12218756", 23, 670, ali.get(5), bi.get(0)));
        jug.add(new Jugador("Nuila", "12235367", 47, 654, ali.get(6), bi.get(0)));
        jug.add(new Jugador("James", "11127789", 33, 377, ali.get(7), bi.get(0)));
        jug.add(new Jugador("Luis", "18956723", 87, 899, ali.get(8), bi.get(0)));
        jug.add(new Jugador("Rigoberto", "11256478", 34, 179, ali.get(9), bi.get(0)));
        
        ActualizarListas();
        for (Jugador jugador : jug) {
            DefaultListModel modelo = (DefaultListModel) jl_jugadores.getModel();
            modelo.addElement(jugador);
        }

    }
    
    private void ActualizarListas(){
        for (Billetera billetera : bi) {
            DefaultListModel modelo = (DefaultListModel) jl_billeteras.getModel();
            modelo.addElement(billetera);
        }
        for (Alimento alimento : ali) {
            DefaultListModel modelo = (DefaultListModel) jl_alimentos.getModel();
            modelo.addElement(alimento);
        }
        for (Categoria categoria : cat) {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_categoria.getModel();
            modelo.addElement(categoria);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Enviar_Solicitud;
    private javax.swing.JMenuItem Seleccionar;
    private javax.swing.JButton bt_aceptar_solicitud;
    private java.awt.Button bt_alimentar;
    private javax.swing.JButton bt_crear_alimento;
    private javax.swing.JButton bt_crear_billetera;
    private javax.swing.JButton bt_crear_categoria;
    private javax.swing.JButton bt_rechazar_solicitud;
    private javax.swing.JComboBox<String> cb_categoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JFormattedTextField jftf_calorias;
    private javax.swing.JFormattedTextField jftf_consumomaximo;
    private javax.swing.JFormattedTextField jftf_costbilletera;
    private javax.swing.JFormattedTextField jftf_costo;
    private javax.swing.JList<String> jl_alimentos;
    private javax.swing.JList<String> jl_amigos;
    private javax.swing.JList<String> jl_billeteras;
    private javax.swing.JList<String> jl_jugadores;
    private javax.swing.JTree jt_categorias;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_nomcategoria;
    private javax.swing.JPopupMenu popup_menu;
    // End of variables declaration//GEN-END:variables
    ArrayList <Billetera> bi = new ArrayList();
    ArrayList <Alimento> ali = new ArrayList();
    ArrayList <Categoria> cat = new ArrayList();
    ArrayList <Jugador> jug = new ArrayList();
    
    DefaultMutableTreeNode nodo_seleccionado;
    Jugador persona_seleccionada;

}
